spring:
  application:
        name: ApiGatewayProjectExample
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: api-1
              uri: lb://WelcomeRestApis
              predicates:
                - Path=/welcome/**
            - id: api-2
              uri: lb://FeignClientProjectTest
              predicates:
                - Path=/test/**
server:
  port: 8889
