server:
  port: 8889
msg: This is the Yml file of ApiGatewayProject
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: api-1
              uri: lb://WelcomeRestApis
              predicates:
                - Path=/welcome/**

            - id: api-2
              uri: lb://FeignClientProjectTest
              predicates:
                - Path=/test/**
