spring:
  application:
        name: FeignClientProjectTest
  boot:
    admin:
      client:
        url: http://localhost:1111/
server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: "*"
